accounts: migrate, setup forwarding to new location, setup server on ./run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,2 +1,31 @@
 #!/usr/bin/env bash
-bundle exec jekyll serve -tw
+set -eu
+
+# https://stackoverflow.com/questions/360201/how-do-i-kill-background-processes-jobs-when-my-shell-script-exits
+trap 'kill $(jobs -p)' EXIT
+
+# Do the initial Jekyll + Asciidoctor build.
+./build
+
+# We used to do:
+#     bundle exec jekyll serve -tw
+# but this fails because Jekyll would remove your generated index.html
+# Having a server is needed to automatically view index.html and to know
+# where the root directory is for / links.
+cd _site
+python -m SimpleHTTPServer &
+cd -
+
+# Auto rebuild.
+file=README.adoc
+atime="$(stat -c %Z "$file")"
+ltime="$atime"
+while true; do
+  atime="$(stat -c %Z "$file")"
+  if [ "$atime" != "$ltime" ]; then
+    echo "rebuild: ${atime}"
+    time ./build-adoc
+    ltime="$atime"
+  fi
+  sleep 1
+done
